name: CI/CD Pipeline

on:
  workflow_call:

jobs:
  build_android:
    name: Android Build and Push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
          channel: 'stable'

      - name: Set up Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/upload-keystore.jks
        working-directory: .

      - name: Set up Google Play Service Account
        run: |
          echo "${{ secrets.PLAY_STORE_JSON_KEY }}" | base64 --decode > android/app/medinest-app-fastlane-key.json
        working-directory: .

      - name: Flutter Clean & Pub Get
        run: |
          flutter clean
          flutter pub get

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile = upload-keystore.jks" >> android/key.properties
        working-directory: .

      - name: Build Flutter App (Android)
        run: flutter build appbundle --release

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'

      - name: Install Fastlane Dependencies
        run: |
          cd android
          gem install bundler:1.17.2
          bundle install

      - name: Run Fastlane for Development Branch
        if: github.ref == 'refs/heads/development'
        run: |
          cd android
          bundle exec fastlane deploy_to_testers
        env:
          AAB_FILE_PATH: ../build/app/outputs/bundle/release/app-release.aab
          PLAY_STORE_JSON_KEY_PATH: ./app/medinest-app-fastlane-key.json

      - name: Deploy to Production (Master Branch)
        if: github.ref == 'refs/heads/master'
        run: |
          cd android
          bundle exec fastlane promote_to_production
        env:
          PLAY_STORE_JSON_KEY_PATH: ./app/medinest-app-fastlane-key.json

