name: Run Tests

on:
  workflow_call:

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dummy step for now"
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Set up JDK
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: "zulu"
      #     java-version: "17"

      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: "3.24.3"
      #     channel: "stable"

      # - name: Install dependencies
      #   run: flutter pub get

      # - name: Run Flutter Analyze
      #   run: flutter analyze

      # - name: Run Flutter Tests
      #   run: flutter test